### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by bsubbaraman**

### CODE REVIEW

**Comment by bsubbaraman** [comment]
Thanks for adding the package test @brendenpelkie! It looks like NumPy 1.19.3 may not yet support Python 3.10. Should we use require python 3.9 for now, or do we have other python 3.10 functionality? If so we could update the numpy version to something compatible?

**Comment by brendenpelkie** [comment]
Yep noticed I broke that on Friday. Fixing it at the moment

**Comment by brendenpelkie** [comment]
@bsubbaraman I fixed my test job file. I'm not sure how to get this to run checks with the updated config - maybe try closing this PR and opening a new one?

**Comment by bsubbaraman** [comment]
Thanks, will do!

**Pull request closed without merging**
